### ISSUE TITLE
Utility to marginalize the SPN

### ISSUE THREAD

**Issue by millerjoey** [trappmartin/SumProductNetworks.jl#11]
Hey Martin, I might be missing something obvious, but is there not yet a way to compute the log marginalized likelihood of the SPN?

i.e. in this mixture of bivariate gaussians, I can't find a way to work with the Normal(-1, 1) + Normal(1,1) mixture.

```
root = FiniteSumNode{Float32}();

add!(root, FiniteProductNode(), Float32(log(0.5))); # Weight 0.5
add!(root, FiniteProductNode(), Float32(log(0.5))); # Weight 0.5

add!(children(root)[1], UnivariateNode(Normal(-1, 1), 1))
add!(children(root)[2], UnivariateNode(Normal(1, 1), 1))
add!(children(root)[1], UnivariateNode(Normal(-1, 10), 2))
add!(children(root)[2], UnivariateNode(Normal(1, 10), 2))
````

**Comment by millerjoey** [comment]
I ended up changing `logpdf!(spn::SumProductNetwork, , x::AbstractVector, llhvals::AxisArray)` so it fills `llhvals` with 0, and added an
```
if node isa Leaf
    if ismissing(x[node.scope])
        continue
     end
end
```
to the inner loop so I just use the log probability of 0 as an input into the Sum/Product node functions.

So now `logpdf(spn, [1,missing])` gets the marginal prob $P(X\_1 = 1)$.

Happy to make my own fork so you can have a look, but I don't want to step on your toes especially if you already have the functionality.

**Comment by trappmartin** [comment]
I already have it on a different branch.

**Comment by trappmartin** [comment]
I’m away from my computer for a few days but will merge the branch by next week.

**Comment by millerjoey** [comment]
Great, looking forward to seeing it!

**Comment by trappmartin** [comment]
I just pushed the code to the current master. I was using `isnan(x[scope(n)])` instead of `ismissing`. This way the data matrix is not a `T <: Union{<:Real,Missing}` but `T <: AbstractFloat` which seemed more convenient at the time. I hope this works for you.

I added a small example to the README.
