### ISSUE TITLE
FiniteSumNode() requires a type declaration

### ISSUE THREAD

**Issue by millerjoey** [trappmartin/SumProductNetworks.jl#6]
Hey, I was trying to run the example code in the readme. First line calls  FiniteSumNode(). It looks like it'll need FiniteSumNode{Float64}() or some other concrete float type. Is this unintended and a bug, or should the readme be updated to reflect that? Thanks!

**Comment by trappmartin** [comment]
Hi, the readme is wrong in these regards. Thanks for reporting!

**Comment by trappmartin** [comment]
Note that there might be some things breaking if you try functionality that is not described in the readme. I’m currently refactoring quite a bit. Sorry for inconvenience.

**Comment by millerjoey** [comment]
No problem. I'll keep an eye on this!

**Comment by trappmartin** [comment]
Great, the package should be in a more stable state once it is officially registered. Which should be very soon.

**Comment by trappmartin** [comment]
Closing for now.
