### ISSUE TITLE
LearnSPN

### ISSUE THREAD

**Issue by klowrey** [trappmartin/SumProductNetworks.jl#8]
Hi Martin,
I was delighted to see an SPN implementation in Julia just as I was starting to dig into them. As part of my exploration, I was wondering if you had a timeline for filling out the generate_spn function, either in this package or another. I'm curious about replacing other function approximators with SPNs in some reinforcement learning projects I have going on; with the right structure, SPNs offer a lot over neural nets for these problems.

Thanks for opening your work!

Kendall

**Comment by trappmartin** [comment]
Thanks for the interest in the package.

I'm currently working on functionality related to AD support and missing values but can clean up my existing structure learning codes (several variants of learnSPN and random structures) to provide some functions asap. I plan to write a library on structure learning for SPNs containing all (or at least most of them) existing approaches in the near future.

**Comment by klowrey** [comment]
When you say 'missing values', do you mean not supplying a full vector of data and allowing the SPN to provide a probability of the values not supplied? In the examples in the readme, this would be like doing something like logpdf with a X vector of length 1 instead of length 2, yes?

**Comment by trappmartin** [comment]
Yes, almost.

I aim to provide a syntax like `logpdf([1.5, NaN])` where the missing value is in dimension 2 and set to NaN. Further, I like to have convenience functions to calculate the approximative MAP for the missing value.

I had part of the functionality some time a go and want to put it in place again. I believe it’s relevant in real world scenarios like robotics.

**Comment by klowrey** [comment]
Very relevant, and one of the use cases I'm hoping SPNs can help with. Thanks for taking the time to implement this in Julia; I'm happy to help in whatever way I can! I have some experience with the Reverse/ForwardDiff.jl packages. Zygote.jl looks interesting, but may not be applicable here without major changes.

**Comment by trappmartin** [comment]
Great to hear that. Feel free to create a PR if you like to contribute something.

I want to have a generic approach so that any AD can be used. As I'm also working on the [Turing.jl](turing.ml) project my aim is to provide example code using ForwardDiff and Flux.Tracker so that SPNs can be used for probabilistic programming within Turing and for deep learning within Flux.

I'll push some parameter learning (log likelihood maximisation) examples asap.

**Comment by trappmartin** [comment]
Thanks to @kouariga there will soon be a clean implementation of `learnSPN`. PR: #12
